from flask import Blueprint, render_template, request, redirect, url_for
from app import mongo
from bson import ObjectId
mod_main = Blueprint('main', __name__)


@mod_main.route('/')
def layout():
	db = mongo.db.arkep
	return render_template("layout.html")

@mod_main.route('/form', methods=['GET','POST'])
def form():
	db = mongo.db.arkep
	if request.method == 'GET':
		emri = "Filan Fistek Filani"
		return render_template("form.html", emri=emri)
	elif request.method == 'POST':
		form_data = request.form.to_dict()
		data = {
		    "nderrmarja":{
		      "emri": form_data['emri_ndermarrjes'],
		      "numri_regjistrimi": form_data['nr_regjistrimit'],
		      "adresa": form_data['adresa'],
		      "personi_kontaktues": form_data['personi_kontaktues'],
		      "telefoni": form_data['telefoni'],
		      "email": form_data['email']
		      },
		      "elementet_rrjetit":{
		        "numri_total_centraleve_telefonike":{
		          "numri_total_centraleve_digjitale":{
		            "sasia": form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "numri_centraleve_analoge":{
		            "sasia": form_data['sasia'],
		            "komente":form_data['komente']
		          }
		        },
		        "kapaciteti_total_centraleve_telefonike":{
		          "sasia": form_data['sasia'],
		          "komente":form_data['komente']
		        }
		      },
		      "infrastruktura_rrjetit_instaluar":{
		        "fiber_optik_instaluar":{
		          "totali_fibrit_optik_instaluar_rrjetin_qasjes":{
		            "sasia":{
		              "km":form_data['km'],
		              "mbps":form_data['mbps']
		            },
		            "komente":form_data['komente']
		          },
		          "totali_fibrit_optik_instaluar_rrjetin_transmetimit":{
		            "sasia":{
		              "km":form_data['km'],
		              "mbps":form_data['mbps']
		            },
		            "komente":form_data['komente']
		          }
		        },
		        "kabell_koaksial":{
		          "totali_kabllit_koaksial_instaluar_rrjetin_qasjes":{
		            "sasia":{
		              "km":form_data['km'],
		              "mbps":form_data['mbps']
		            },
		            "komente":form_data['komente']
		          },
		          "totali_kablli_koaksial_instaluar_rrjetin_transmetimit":{
		            "sasia":{
		              "km":form_data['km'],
		              "mbps":form_data['mbps']
		            },
		            "komente":form_data['komente']
		          }
		        },
		        "lidhja_radiofrekuenca_mikrovalore":{
		          "sasia":{
		            "km":form_data['km'],
		            "mbps":form_data['mbps']
		            },
		            "komente":form_data['komente']
		          }
		       },
		       "numri_perdoruesvefundore_regjione":{
		         "regjioni":{
		           "prishtina":{
		             "prishtina":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "podujeva":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "drenasi":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "fushe_kosova":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "obiliqi":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "lipjani":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "graqanica":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "novoberda":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             }
		           },
		           "mitrovica":{
		             "mitrovica":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "vushtria":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "skenderaji":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "zubin_potoku":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "zvecan":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "leposaviq":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             }
		           },
		           "peja":{
		             "peja":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "gjakova":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "deqani":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "klina":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "istogu":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "juniku":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "rahoveci":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             }
		           },
		           "prizreni":{
		             "prizreni":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "suhareka":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "dragashi":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "malisheva":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "mamusha":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "gjilani":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "ferizaji":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "vitia":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "kamenica":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             }
		           },
		           "gjilani":{
		             "hani_i_elezit":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "kacaniku":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "shtime":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "shterpc":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "kllokot":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "Ranilug":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             },
		             "parteshi":{
		               "kabina_telefonike":form_data['kabina_telefonike'],
		               "pstn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "isdn":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		               },
		               "voip":{
		                 "individual":form_data['individual'],
		                 "biznes":form_data['biznes']
		                 },
		               "total":form_data['total'],
		               "komente":form_data['komente']
		             }
		           }
		         }
		        },
		        "numri_perdoruesve_sherbimet_integruara":{
		          "telefoni_interneti":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "telefoni_tv":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "telefoni_interneti_tv":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "tjera":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          }
		        },
		        "trafiku":{
		          "origjinimi_terminimi_thirrjeve_rrjetin_vet":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "origjinimi_thirrjeve_rrjetet_tjera_fikse":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "origjinimi_thirrjeve_rrjetit_mobil":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "origjinimi_thirrjeve_rrjetit_nderkombetar":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "terminimi_thirrjeve_rrjetet_fikse":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "terminimi_thirrjeve_rrjetet_mobile":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "terminimi_thirrjeve_rrjetet_nderkombetare":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "trafiku_total_telefonit":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          }
		        },
		        "trafiku_realizuar":{
		          "origjinimi_terminimi_thirrjeve_rrjetin_vet":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "origjinimi_thirrjeve_rrjetet_tjera_fikse":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "origjinimi_thirrjeve_rrjetit_mobil":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "origjinimi_thirrjeve_rrjetit_nderkombetar":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "terminimi_thirrjeve_rrjetet_fikse":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "terminimi_thirrjeve_rrjetet_mobile":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "terminimi_thirrjeve_rrjetet_nderkombetare":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "trafiku_total_telefonit":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "kohezgjatja_mesatare_thirrjes":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          }
		        },
		        "tarifat_e_tanishme":{
		          "thirrjet_brenda_rrjetit":{
		            "thirrjet_lokale":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            },
		            "thirrjet_kombetare":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            },
		            "thirrjet_rrjeteve_tjera_fikse":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            },
		            "thirrjet_rrjetit_mobil1":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            },
		            "thirrjet_rrjetit_mobil2":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            },
		            "thirrjet_rrjetit_mobil3":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            },
		            "thirrjet_rrjetit_mobil4":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		              },
		              "komente":form_data['komente']
		            }
		          },
		          "thirrjet_drejt_shteteve_tjera":{
		            "shqiperia":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "maqedonia":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "mal_zi":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "serbi":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "kroaci":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "bosnje_hercegovina":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "turqi":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "gjermani":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "itali":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "france":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "zvicer":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "uk":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "usa":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            },
		            "kanada":{
		              "qmimi":{
		                "peak":form_data['peak'],
		                "off_peak":form_data['off_peak']
		                },
		              "komente":form_data['komente']
		            }
		          }
		        },
		        "informacione_tjera_rreth_cilesise_sherbimit":{
		          "koha_mesatare_instalimit_linjes_telefonike":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "tarifat_kyqjes":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "tarifa_mujore_qerase":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "numri_defekteve_raportuara":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "numri_ankesave_nga_perdoruesi":{
		            "perfaturim":{
		              "sasia":form_data['sasia'],
		              "komente":form_data['komente']
		            },
		            "tetjera":{
		              "sasia":form_data['sasia'],
		              "komente":form_data['komente']
		            }
		          },
		          "kontributi_sherbime_universale":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          },
		          "sasia_pranuar_sherbime_universale":{
		            "sasia":form_data['sasia'],
		            "komente":form_data['komente']
		          }
		       },
		       "interkoneksioni":{
		         "kombetar_fiks_fiks":{
		           "peak":form_data['peak'],
		           "offpeak":form_data['off_peak'],
		           "komente":form_data['komente']
		         },
		         "kombetar_mobil_fiks":{
		           "peak":form_data['peak'],
		           "offpeak":form_data['off_peak'],
		           "komente":form_data['komente']
		         },
		         "nderkombetar_kombetar":{
		           "peak":form_data['peak'],
		           "offpeak":form_data['off_peak'],
		           "komente":form_data['komente']
		         },
		         "tranzit_kombetar_fiks":{
		           "peak":form_data['peak'],
		           "offpeak":form_data['off_peak'],
		           "komente":form_data['komente']
		         },
		         "tranzit_nderkombetar_kombetar":{
		           "peak":form_data['peak'],
		           "offpeak":form_data['off_peak'],
		           "komente":form_data['komente']
		         }
		       },
		       "transferimi_tedhenave":{
		         "sasia_tedhenave_transferuaru_trafikin_kombetar":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "sasia_tedhenave_transferuaru_trafikin_nderkombetar":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "shume_totale_tedhenave_transferuara":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       },
		       "te_hyrat":{
		         "teardhurat_trafiku_rrjetin_vet":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_trafiku_rrjet_tjera_caktuara_shumice":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_trafiku_rrjet_tjera_caktuara_pakice":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_trafiku_rrjet_tjera_mobile_shumice":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_trafiku_rrjet_tjera_mobile_pakice":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_trafiku_nerkombetare_telefonik_pakice":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_trafiku_nerkombetare_telefonik_shumice":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_ofruesit_sherbimeve_cmime_veqante_kosto":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_nga_dialup_qasje_internet":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_nga_ofruesit_sherbimeve_voip":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_tjera":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "teardhurat_gjithsej":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       },
		       "fitimi_para_tatimit":{
		         "ebit":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "ebitda":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "roce":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "ebitda_margina":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "ebit_margina":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       },
		       "shpenzimet":{
		         "shpenzimet_totale":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       },
		       "zhvleftsimi_amortizmi":{
		         "zhvleftsimi":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "amortizmi":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       },
		       "investimet_sherbime_infrastrukturen_telekomunikuese":{
		         "investime_sherbime_infrastrukturen_telekomunikuese":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "investime_infrastrukture_rrjetin_backbone":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "investime_infrastrukture_rrjetin_qasjes":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "investime_hulumtime_zhvillim_produkteve":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "shpenzimet_marketing":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "shpenzimet_tjera":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "totali":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       },
		       "tedhenat_numrin_puntoreve":{
		         "numri_puntoreve_orari_plote_punes":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "numri_puntoreve_orari_pjeseshem_punes":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         },
		         "totali_punetoreve":{
		           "sasia":form_data['sasia'],
		           "komente":form_data['komente']
		         }
		       }
        }

		db = mongo.db.arkep
		db.insert(data)
		return render_template("form.html", mesazhi="Faleminderit, forma u insertua")
	else:
		return "Go home, you are drunk"

@mod_main.route('/list', methods=['GET'])
def list():
	db = mongo.db.arkep
	rekordet = db.find()
	return render_template('list.html', rekordet=rekordet)

@mod_main.route('/remove/<string:remove_id>',methods=['POST'])
def remove(remove_id):
    db=mongo.db.arkep
    remove=db.remove({"_id":ObjectId(remove_id)})
    return Response(200)

@mod_main.route('/raporti/<string:report_id>')
def raporti(report_id):
	db = mongo.db.arkep
	report = db.find_one({ "_id" : ObjectId(report_id) })
	return render_template('raporti.html',report=report)
